### ISSUE TITLE
Updater fails to detect the availability of a new update when Orbot is in VPN-mode

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/platform_packages_apps_Updater#24]
GrapheneOS updater fails to detect the availability of a new update when running Orbot in full-device VPN-mode. This has happened several times before, tested on sargo and bonito on stable. Once Orbot and the related VPN settings are deactivated, the update process starts immediately.

This is in contrast to the information on the website, where it says "The update protocol [...] works well over a VPN / Tor".

**Comment by thestinger** [comment]
Do you have it set to work on any network? Orbot likely has itself marked as a metered network since it can use mobile data.

**Comment by ghost** [comment]
Yes, "permitted networks" is set to "any". Channel is "stable", and the battery warning option is obviously deactivated.

My gut feeling is that is has something to do with "permitted networks" though, perhaps it somehow clashes with Orbot specifically.

**Comment by thestinger** [comment]
If that's set to any, then I don't see how it would prevent this from working. The only issue that I could see is that if the connectivity checks are detecting the network as not working.

**Comment by thestinger** [comment]
Are you sure the exit node was not blocking the connections?

**Comment by thestinger** [comment]
You can use `adb logcat` to see output from Updater. Try using Orbot again and checking for updates. If it's successfully connecting then I don't see an issue. I don't see any way of addressing this if it simply wasn't working for you one time. Exit nodes are often really sketchy.

**Comment by ghost** [comment]
As I said, the issue persisted over several months, across multiple devices. That would rule out broken exit nodes. I'm quite confident it has actually never worked, I had to disable full-device VPN-mode in Orbot and grant the updater clearnet access.

I have a spare 3a, will set it up and run logcat. Will post the results here.

**Comment by thestinger** [comment]
I don't really understand how it could fail to work for you.

**Comment by thestinger** [comment]
@alex-resist Any update on this?

**Comment by ghost** [comment]
I think this issue can be closed. I've tried to reproduce it over the last couple of releases. It worked right away on sargo through Orbot. On my personal bonito, it worked most of the time. Sometimes there was a latency of several seconds until a new release was detected, and with 2021.03.06.00 it didn't work for hours, although there clearly was a new stable release. One day later or when switching to beta, it eventually worked.

I conclude that this is probably not an issue with GrapheneOS, but with Orbot connectivity. Still, it is not always reliable, and there is a chance that people running GrapheneOS and routing all their traffic through Orbot will not receive updates in time. So I'm closing this with a caveat.
