### ISSUE TITLE
Updater doesn't allow wildcard certificates

### ISSUE THREAD

**Issue by hmenke** [GrapheneOS/platform_packages_apps_Updater#46]
When the domain is covered by a wildcard certificate the updater fails with
```
Hostname example.com not verified: certificate: sha1/... DN: CN=:*.example.com subjectAltNames: [*.example.com]
```

**Comment by thestinger** [comment]
A certificate for *.example.com doesn't cover example.com. It needs to have both *.example.com and example.com in subjectAltNames.

It's just the normal way certificate validation works when there aren't compatibility hacks active.

**Comment by hmenke** [comment]
> A certificate for *.example.com doesn't cover example.com

Interesting. Chromium accepts this certificate. Anyway, it's no big deal adding `example.com` to the names. Thanks.

**Comment by thestinger** [comment]
Browsers have weird compatibility hacks.
