### ISSUE TITLE
avoid service being interrupted by settings activity being closed in recent apps

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/platform_packages_apps_Updater#5]

**Comment by grote** [comment]
Maybe it would help to use the newly added notifications to start a foreground service. This way, there will at least be no interruption during download and install.

Another uglier fix could be to exclude the activity from recent apps. This makes it only less likely that the user finds a way to close the app.

**Comment by thestinger** [comment]
A foreground service may be reasonable as long as it's actually allowed to start one (not sure it is) and keep it running across the changes in the notification.

**Comment by thestinger** [comment]
I expect that this isn't an issue anymore due to the foreground service.
