### ISSUE TITLE
Don't perform major version upgrades silently

### ISSUE THREAD

**Issue by laszlovl** [GrapheneOS/platform_packages_apps_Updater#50]
Earlier this week I received a notification from the updater app that a new release was downloaded, installed and ready to apply upon reboot. I ignored the notification on purpose because I had a busy day and didn't want to be interrupted. However, shortly afterwards my phone somehow rebooted by itself and thereby automatically applied the upgrade. To my surprise, the release turned out to be a major upgrade from Android 11 to Android 12 that contained various bugs/changes and a completely new (awful) UI. Having to deal with this came at a very inconvenient time.

I would urge to:

1. Never perform major version upgrades silently, e.g. without an acknowledgement from the user that they're ready to perform a major upgrade and deal with the consequences that come with it.

2. Even for minor upgrades, don't force them onto people with a mechanism they have zero control over. Make it possible to cancel an update (or at least make it not apply automatically on the next reboot just yet), or if that's not possible add a preference to the updater app to automatically download but not install & apply new releases. There are a dozen conceivable situations where your phone's stability is temporarily more important than running on the latest release.

**Comment by thestinger** [comment]
You have control over it, it's not silent, and it's not simply a major version upgrade but also a security update.

**Comment by laszlovl** [comment]
The update downloaded automatically (can't be disabled), installed automatically (can't be disabled), applied automatically (as soon as the phone rebooted itself). At which point could you have had any control over it?

Security updates are obviously important, but not at any cost. If you absolutely _need_ your phone to be stable for a day (for important communication, being able to pay, check in to public transport, etc) you must have the option to postpone the update until you're back home and able to deal with the fallout of apps breaking or worse.

**Comment by thestinger** [comment]
We're not going to have a separate policy for some updates. Updates are updates.

**Comment by thestinger** [comment]
There's 1 supported version of the OS and every update to it is going to be treated the same. It sounds like you want a separate LTS channel and that's not possible to support right now, but that's how we would support this. We aren't handling some updates via a release channel differently. It's not the design approach.

**Comment by laszlovl** [comment]
No, I don't think that you understand my issue. I'm not asking for a LTS channel or a change to your release policy. I'm merely saying that you should have some kind of control (at the very least for major version upgrades) about _when exactly_ the update is applied to your phone, so that you don't risk your phone suddenly breaking at a time where it's really not convenient.

For anyone else reading this, I found that the following steps should probably prevent the update from being silently/automatically applied upon reboot: enable developer options if you haven't already done so, search for "automatic system updates" and turn it off.

**Comment by thestinger** [comment]
There's no distinction between minor and major version upgrades.

**Comment by thestinger** [comment]
> For anyone else reading this, I found that the following steps should probably prevent the update from being silently/automatically applied upon reboot: enable developer options if you haven't already done so, search for "automatic system updates" and turn it off.

That doesn't do anything. Our usage guide covers how to do that.

**Comment by laszlovl** [comment]
> There's no distinction between minor and major version upgrades.

I still think you're not understanding my main point at all, so I'll stop trying to beat a dead horse. Hopefully someone else will be able to convince you that users should be able to control for themselves when their phone will apply a (major) version upgrade.

**Comment by thestinger** [comment]
Every upgrade is potentially major. It can't and won't be treated separately. LTS branches are something that can exist later, but cannot currently be supported because the supported devices don't do it.

**Comment by User10987654321** [comment]
> Every upgrade is potentially major. It can't and won't be treated separately. LTS branches are something that can exist later, but cannot currently be supported because the supported devices don't do it.

It doesn't matter how major the update is; like @laszlovl said, the user's control should be priority in a 'security-prioritizing' operating system as opposed to whatever spy agency runs this shitty repository if they truly believe user's shouldn't have the ability to control system updates.
