### ISSUE TITLE
Updater won't update

### ISSUE THREAD

**Issue by Robinhio83** [GrapheneOS/platform_packages_apps_Updater#53]
Pixel 5
Build SP1A.210812.015.2021102613

Updater won't update to the newest build. If I manually trigger the check for new updates it downloads something around 20-50MB of data, after that I get nothing.
Tried to reset the updater app by disabling it and deleting its cache and user-files.

**Comment by thestinger** [comment]
I think you need to ask for support on Matrix for this issue. Don't think it's a bug.
