### ISSUE TITLE
Should changing release channel trigger an immediate upgrade?

### ISSUE THREAD

**Issue by s00se** [GrapheneOS/platform_packages_apps_Updater#56]
Currently, changing the release channel from stable to beta seems to cause an immediate download and upgrade (depending if automatic reboot is selected), which doesn't seem to have the option to cancel during the process.

b45f0757093e0f3bcc4cb5823d6bb6b14ca2beb8 ?

Would it be possible to have an option somewhere in the process of selecting stable to beta or vice-versa to cancel this, in the event that the user change their mind, or even in case the user tapped the wrong selection?

**Comment by thestinger** [comment]
Note that you could just switch back and reboot. It's harmless to reboot during the update process. It's entirely safe to reboot even in the middle of installation. We could add an explicit way to cancel but rebooting or force stopping Updater will effectively cancel it. It would just normally try to start the update again later. I don't really recommend force stopping it unless you make sure to open up the update settings to get it started again and then reboot so it registers the jobs again. It's easier to just reboot.

**Comment by s00se** [comment]
Thanks for clarifying, makes sense. This would be useful to have, but as you mentioned it shouldn't have any "functional" impacts if interrupted or switching between channels.
