### ISSUE TITLE
[feature/suggestion| Add option to disable (temporarly) checking for updates/downloading updates

### ISSUE THREAD

**Issue by mjnck** [GrapheneOS/platform_packages_apps_Updater#69]
Would be nice to have feature to disable checking or downloading updates. For example not to make connections to grapheneos update servers, also to postpone updates if you can't have a situation where  something on the phone doesn't work because of an update.
Of course this option should warn user that it can make phone insecure.

**Comment by x86pup** [comment]
https://grapheneos.org/usage#updates-disabling

**Comment by mjnck** [comment]
Ok, i know that whole app can be disabled but special option with warning about consequences of turning off updates will look more polished than turning off the app

**Comment by thestinger** [comment]
There are plans to add options similar to the update client but not like this which is already possible.
