### ISSUE TITLE
consider adding the "update only via Wifi" option

### ISSUE THREAD

**Issue by Gospodininzenjer** [GrapheneOS/platform_packages_apps_Updater#71]
due to frequent updates lately, users who have Internet packages with limited monthly capacities very quickly run out of Intentnet credit due to updates when they are away from home or out of Wi-Fi range.  You could add the "update only via Wifi" option.  to update only when the user is on Wi-Fi, to avoid using up mobile internet.  
thanks in advance

**Comment by matchboxbananasynergy** [comment]
This can be done at: Settings > System > System Update.

Under Permitted networks, choose "unmetered".

Also, please keep in mind that the correct issue tracker for this kind of thing would be this one:

https://github.com/GrapheneOS/os-issue-tracker

This tracker is for the OS's website, not the OS itself.

**Comment by Gospodininzenjer** [comment]
Thanx
