### ISSUE TITLE
[Feature Request] Option to only download updates when connected to a charger and at scheduled times

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/platform_packages_apps_Updater#75]
The process of downloading and installing system updates can be somewhat battery intensive. I'd like the ability to only do so when connected to a charger and within a specific time window.

Here's the options Neo Store gives for syncing F-Droid repositories.

![Screenshot_20230315-175116](https://user-images.githubusercontent.com/128001567/225483819-7d5bccde-d4ab-40e2-ab79-d6e7c383a085.png)

Here's how AntennaPod let's the user chose between an interval or at a specific time.

![Screenshot_20230315-191154](https://user-images.githubusercontent.com/128001567/225484142-d2ee0845-a462-4797-931b-bc02536dcb87.png)

**Comment by dd-dreams** [comment]
Is there any difficulty implementing the first request?

**Comment by useross** [comment]
The last update started when my phone was at 12% battery status and the phone was in the energy-saving-mode. The battery went empty during the update. Luckily the phone was able to start as normal as usual when I reconnected it to a charger. This was a very risky thing. 

So I`d also like to ask for a similar feature:
 * what about introducing a minimum battery level e.g. of 30% before downloading and installing the update?
 * disable updates when the phone is in battery-saving-mode

Maybe these things can be set as a default option, to avoid such risky update processes.

**Comment by thestinger** [comment]
There's already a toggle for low battery. There could also be a toggle for only doing it while charging. That would be easy to add.

**Comment by useross** [comment]
Nice! Thanks for this information, i was not aware of this.
Does it make sense to enable the `Require battery above warning level` by default? From my point of view, it makes sense to enable this feature for all users by default, to avoid an empty battery while updating.

**Comment by thestinger** [comment]
It's not supposed to use nearly as much power as it does now due to Android 14 regressions and earlier regressions.

**Comment by thestinger** [comment]
Option to require charging added for next release. Not currently going to change the defaults. No plan to add scheduled times since JobScheduler doesn't support it directly and implementing it with hacks wouldn't work well.
