### ISSUE TITLE
[Feature Request] Ability to trigger a check for updates and/or download and install by a broadcast

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/platform_packages_apps_Updater#76]
The ability to check for updates or download/install using a broadcast/Android Intent so it can be trigger via shell scripts or automation apps such as Tasker or Easer.

Here's how AntennaPod does it: [https://antennapod.org/documentation/automation/tasker](https://antennapod.org/documentation/automation/tasker)

**Comment by thestinger** [comment]
We don't plan on supporting this.
