### ISSUE TITLE
Request: Update changelog on the System Update menu

### ISSUE THREAD

**Issue by timonoj** [GrapheneOS/platform_packages_apps_Updater#80]
Hi guys!

I really think these updates changelogs you publish on links should show the text on some option on the system update menu. I think this whole menu should show a description of what’s your current version (not shown on system update section), the newer update number and date, and a summary of what it entails. I find the current updating process rather… Obscure…You don't know where you stand, where are you going to, and what could happen along the way. Samsung (and most other providers) do provide a lot more details about what's about to happen if you proceed. Graphene does not.

Thanks!

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/67
