### ISSUE TITLE
Show a changelog

### ISSUE THREAD

**Issue by chirayudesai** [GrapheneOS/platform_packages_apps_Updater#9]
Show a changelog for the updates.

I have a WiP implementation ready which fetches the changelog as HTML from the server and shows it via HTMLViewer (which is what Settings -> About -> Legal) uses.

HTMLViewer is locked down, no js, no internet access, so it seemed like the best way to have something with formatting.

**Comment by chirayudesai** [comment]
![Screenshot_20190814-024823](https://user-images.githubusercontent.com/952062/63266878-84d28d00-c2ae-11e9-9e01-6756dde18a84.png)

This is what it looks like right now, https://gitlab.com/calyxos/platform_packages_apps_updater/commit/32b01f4559d6bce92b34d4e7760db08369894271 WiP

Need to figure out text wrapping. Also the view can be freely zoomed in and out of, and also scrolled.

**Comment by thestinger** [comment]
Replaced with https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/22. We would prefer to reuse the release notes on the site for this.
