### ISSUE TITLE
Unexpected default for permitted networks

### ISSUE THREAD

**Issue by ungive** [GrapheneOS/platform_packages_apps_Updater#92]
Thank you for your efforts on GrapheneOS, I love it so far!

Today I noticed that within 10 days the system updater used over 500 MB of my mobile data to download updates in the background. I wasn't aware of it and was a little upset to see that, as I would never expect large downloads to be made over metered connections by default.

I can see reasoning for this, as a security-first operating system should have sensible defaults for features relevant to security (timely and fast updates), so I'm not even going to suggest changing this default.

What I would like to suggest instead is to maybe add a hint in the "Post-installation" section of the installation guides, that updates are downloaded on metered networks by default and that if the user wants to change that, they should do so in the settings. I read the installation guide top-to-bottom (obviously), but I didn't read everything in the usage guide extremely thoroughly, so I missed that even metered networks are used by default, until I noticed it today.

I think a small hint like that would be a nice heads-up! I'd be happy to hear your opinions.

**Comment by thestinger** [comment]
The default for Updater and Apps is going to remain any network. Apps likely uses more bandwidth. We don't plan to change this or encourage people to set it to Unmetered. The option is there for people who want it.

**Comment by ungive** [comment]
> The default for Updater and Apps is going to remain any network.

I figured!

> Apps likely uses more bandwidth.

The system updater uses the most bandwidth of all apps, by far.

> We don't plan to change this or encourage people to set it to Unmetered.

My issue is about informing the user about the setting, not encouraging or suggesting to change it.

> The option is there for people who want it.

I'm glad it is, thank you!
