### ISSUE TITLE
Update has been installed while the device was discharging and in battery saving mode

### ISSUE THREAD

**Issue by ungive** [GrapheneOS/platform_packages_apps_Updater#93]
My phone was at 32%, not charging and in battery saving mode. My system update settings were the following:
- Require battery above warning level: yes
- Require device to be charging: yes

I manually pressed on "Check for updates (Tap to check for updates)", I then got a notification that said it was installing the update and verifying it. The notification after that said "Update successfully installed (Please reboot ...)".

I don't know if the update would have been installed in the background too, without me pressing the "Check for updates" button, but it's unexpected for me that updates are *installed*, when I merely want to *check* for new updates. Even if I wanted to install the updates, it should have maybe refused to or warned me, as the phone was not charging and I wished for it to be charging while installing (as per my settings above).

Either the wording of the button is misleading or the button does more than it should!

**Comment by thestinger** [comment]
Manual check for updates was recently improved to bypass the constraints. This is how it's intended to work right now.
