### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by RufenKhokhar** [GrapheneOS/platform_packages_apps_Updater#94]
Please write a quick  guide on how to build this project

**Comment by thestinger** [comment]
It's built as part of GrapheneOS.

https://grapheneos.org/build

**Comment by RufenKhokhar** [comment]
Thanks for the answer, but I want to build this for Android OS, and I have zero experience with this kind of app. So, Please write in simple steps.

**Comment by thestinger** [comment]
It's built as part of the OS, not separately.

**Comment by RufenKhokhar** [comment]
So, when I build the os it will be included automatically?

**Comment by thestinger** [comment]
If you add it to the OS tree and add it to PRODUCT_PACKAGES.

**Comment by RufenKhokhar** [comment]
Actually, i have zero experience, if you feel easy, please give me reference how i add it to os tree and product packages.

**Comment by RufenKhokhar** [comment]
I found a tutorial how build this, but i don't know how to add it to the project tree. 
Tutorial link. 
https://youtube.com/playlist?list=PLsljP0DCGt1EixatPHcvrnY4vswEGHQrp&si=p0lrUv-3zuAxLf4v
